In [3]:
!pip install torch torchvision

  Attempting uninstall: torch
    Found existing installation: torch 1.13.0
    Uninstalling torch-1.13.0:
      Successfully uninstalled torch-1.13.0


In [6]:
import torch

In [7]:
# 1. Создайте случайный FloatTensor размера 3x4x5
a = torch.randn(3, 4, 5)

In [8]:
# 2. Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [9]:
# 3. Приведите его к форме 6х10
a = a.reshape(6, 10)
a.shape

torch.Size([6, 10])

In [10]:
# 4. Создайте случайный IntTensor размера 10
b = torch.randint(10, size=(10,)).int()
b.type()

'torch.IntTensor'

In [11]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
a * b

tensor([[ -0.4398,   2.0790,   2.6691,  -3.4514,  -2.4113,   0.9390,   0.0259,
          -2.1647,   0.1529,   2.3834],
        [  1.5427,   9.1442,   0.8318,  -0.0229,  -5.8378,   0.7735,  -1.1669,
           2.2301,  -1.2895,   1.6378],
        [  2.1331,  -0.0192,   0.9880,  -4.9189,   1.1006,   1.1309,  -1.6619,
           1.7740,   3.5215,  -4.2174],
        [ -0.6965,   4.9581,  -0.0671,  -1.1094,  11.2336,   1.0895,   0.2931,
           1.1465,   2.5832,   3.9368],
        [  1.4519,   5.6182,  -2.8465,   0.5805, -15.3987,  -0.6378,  -0.1751,
          -0.8055,   2.2953, -10.3086],
        [  0.6245,   0.9331,  -2.8974,   0.0740,  11.0712,  -1.9877,   1.4818,
           1.3584,  -5.6897,  -5.3402]])

In [12]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
torch.matmul(a, a.T)

tensor([[ 7.4750,  0.3351,  3.6267,  1.7818, -3.0679, -5.9317],
        [ 0.3351,  9.0665,  6.4106, -0.1333,  3.1639, -2.7652],
        [ 3.6267,  6.4106, 17.7848,  1.7118,  3.1808, -4.6596],
        [ 1.7818, -0.1333,  1.7118,  7.0151, -5.8225, -1.5561],
        [-3.0679,  3.1639,  3.1808, -5.8225, 15.3694,  1.1313],
        [-5.9317, -2.7652, -4.6596, -1.5561,  1.1313, 16.3613]])

In [13]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1]).float()
x.requires_grad = True
z = torch.tensor([.5]).float()
z.requires_grad = True
t = torch.tensor([2]).float()
t.requires_grad = True
y = x**3 + z - 75*t
y.backward()
print(x.grad, z.grad, t.grad)

tensor([3.]) tensor([1.]) tensor([-75.])


In [14]:
# 8. Создайте единичный тензор размера 5x6
c = torch.ones((5, 6))
c

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [15]:
# 9. Переведите его в формат numpy
d = c.numpy()
d 

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)